### ISSUE TITLE
Still maintained / planned any release

### ISSUE THREAD

**Issue by infodroid** [michael-simons/java-autolinker#2]
I see its last commits before year. Is it still maintained ? Do you plan to release this project and and host artifacts any maven repositories.

Thanks,

**Comment by michael-simons** [comment]
Hi,

I'm using this module pretty active on my daily picture project
https://dailyfratze.de.

I can release an artifact of course, no problem.

Also, if someone is interested, i have a complete rewrite with actual great
test coverage leveraging Java 8 features.

The current module works for me pretty well and I didn't found any hard
bugs or problems, which is the reason for missing commits.

Cheers,
Michael
Am 01.04.2015 12:04 schrieb "infodroid" <notifications@github.com>:

**Comment by infodroid** [comment]
Hello Michael,

If you can release current version, it will be a great help.

I would prefer to see the Java 8 port if already with you, is it open
sourced ?.

Thanks,
Jigar Shah.

**Comment by michael-simons** [comment]
Hi Jigar,

the current code has dependency on a pretty much senseless library… I must remove that, than i can build a release.

I’ll let you know when it’s ready.

Cheers,
Michael

**Comment by michael-simons** [comment]
If you have some time on your hands, i'll wrap up the Java 8 version… Its much nicer but only works on JDK8.

**Comment by infodroid** [comment]
I can wait for JDK8 compitible release.
But current code release artifact is critical.

**Comment by michael-simons** [comment]
Hi,
Updated version (Java 8 only), should be available in few hours on maven central at coordinates

```
<dependency>
    <groupId>eu.michael-simons</groupId>
    <artifactId>java-autolinker</artifactId>
    <version>0.1.1</version>
</dependency>
```

Please note that I'l gladly accept pull requests but this is not a full time project for me at the moment. Currently it works perfect for me and has 100% test coverage for my use cases.

Would be happy to know where you plan on using it :)

**Comment by infodroid** [comment]
Thanks, I can now start using it. 

I am developing search engine for patient documents. These documents has references section (mostly supplied as text). Some times hyperlinks appear in this section, and user needs to copy the links and paste in new browser tab to futher navigate.

This library helps to identify links from references section, highlight them, and helps user to navigate on them directly.

Thanks once again !!
